# Generated by Django 2.1.1 on 2018-09-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField()),
                ('abstract', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('text', models.CharField(max_length=25000)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('links', models.CharField(max_length=30000)),
                ('times', models.CharField(max_length=30000)),
            ],
        ),
        migrations.AddField(
            model_name='abstract',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Detail'),
        ),
    ]
