# Generated by Django 2.1.1 on 2018-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='links',
            field=models.CharField(max_length=300000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='times',
            field=models.CharField(max_length=300000),
        ),
    ]
