# Generated by Django 2.1.1 on 2018-09-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180912_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='detail',
        ),
    ]
