# Generated by Django 2.1.1 on 2018-09-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_abstract_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abstract',
            new_name='Item',
        ),
    ]
