# Generated by Django 2.1.1 on 2018-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180912_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField()),
                ('abstract', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
