# Generated by Django 2.1.1 on 2018-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180912_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='links',
            field=models.CharField(default='', max_length=100),
        ),
    ]
